### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by filoxo**
This pull request includes the following changes:
- Color variables, in their own files
- Better modularization of components
- Alphabetization of colors and properties
- Various other little things, like formatting :tada: 

Other considerations: 
- While the above improvements have been helpful to me, compiling from sass now takes longer (~6 seconds).

### CODE REVIEW

**Comment by matheusrocha89** [comment]
I think the compilation time will not be a problem, maybe updating to a new version is performance will be better.

**Comment by matheusrocha89** [comment]
Looking at the CI there was an error message:

```
[03:10:51] Starting 'sass'...
Error in plugin 'sass'
Message:
    sass/ionic-flat.scss
Error: Import directives may not be used within control directives or mixins.
        on line 15 of sass/ionic-flat.scss
>>     @import "bars/bars";
   ----^
```

**Comment by filoxo** [comment]
The problem stemmed from the version of `gulp-sass` (which has a dependency on `node-sass`) I had installed, though I forgot to check which version before blowing it all away. My bad. Updated to latest locally, researched the problem, made fixes. CI builds without errors now. :rocket:

**Comment by matheusrocha89** [comment]
Thanks for your contribution @filoxo

**Pull request merged**
